AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions OIDC Identity Provider and IAM Roles for CI/CD'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization or username
    Default: "your-github-org"
  
  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: "jewelry-manufacturing"
  
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    AllowedValues: [dev, staging, prod]
    Default: "dev"

Resources:
  # GitHub OIDC Identity Provider
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      Tags:
        - Key: Name
          Value: !Sub "github-actions-oidc-${Environment}"
        - Key: Environment
          Value: !Ref Environment

  # IAM Role for GitHub Actions
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "github-actions-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GitHubOIDCProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubOrg}/${GitHubRepo}:*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      Policies:
        - PolicyName: GitHubActionsDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudFormation permissions
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"
              
              # IAM permissions for SAM deployments
              - Effect: Allow
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PassRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:ListRoleTags
                  - iam:UpdateRole
                  - iam:UpdateRoleDescription
                Resource: 
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/jewelry-*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/sam-*"
              
              # Lambda permissions
              - Effect: Allow
                Action:
                  - lambda:*
                Resource: "*"
              
              # API Gateway permissions
              - Effect: Allow
                Action:
                  - apigateway:*
                Resource: "*"
              
              # S3 permissions
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              
              # CloudFront permissions
              - Effect: Allow
                Action:
                  - cloudfront:*
                Resource: "*"
              
              # Secrets Manager permissions (environment-specific)
              - Effect: Allow
                Action:
                  - secretsmanager:*
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:jewelry-manufacturing-${Environment}-*"
              
              # CloudWatch Logs permissions
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"
              
              # Application Auto Scaling permissions
              - Effect: Allow
                Action:
                  - application-autoscaling:*
                Resource: "*"
      Tags:
        - Key: Name
          Value: !Sub "github-actions-role-${Environment}"
        - Key: Environment
          Value: !Ref Environment

Outputs:
  GitHubOIDCProviderArn:
    Description: ARN of the GitHub OIDC Identity Provider
    Value: !Ref GitHubOIDCProvider
    Export:
      Name: !Sub "${AWS::StackName}-GitHubOIDCProviderArn"
  
  GitHubActionsRoleArn:
    Description: ARN of the GitHub Actions IAM Role
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GitHubActionsRoleArn"
  
  GitHubActionsRoleName:
    Description: Name of the GitHub Actions IAM Role
    Value: !Ref GitHubActionsRole
    Export:
      Name: !Sub "${AWS::StackName}-GitHubActionsRoleName"